Daniel
madamczak/ZamenaKurs pull request #2
Opened 2021-02-09 21:53 UTC by ebpblmah

2021-02-10 11:10 UTC, madamczak commented on .gitignore
> +.vscode/.ropeproject/objectdb
dodaj tutaj całą ścieżkę .vscode./ropeproject/ a nie 2 oddzielne pliki

2021-02-10 11:15 UTC, madamczak requested changes
pierdoły do poprawy

2021-02-10 11:15 UTC, madamczak commented on dzien3funkcje/daniel/zadaniadzien3.py
> +        return print("incorrect input parameter, must be list of ints")
tutaj musisz się zdecydować czy robić return "..." czy samo print. return print(...) wyprintuje stringa a funkcja zwróci None

2021-02-15 23:25 UTC, ebpblmah commented on dzien3funkcje/daniel/zadaniadzien3.py
> +        return print("incorrect input parameter, must be list of ints")
teraz już rozumiem

2021-02-15 23:28 UTC, ebpblmah commented on dzien3funkcje/daniel/zadaniadzien3.py
> +print(random_daytime3b(5))
oczywiście odnosiłem się do funkcji z poprzedniego zadania i dlatego nie działało, teraz już powinno być ok

2021-02-15 23:30 UTC, merged